name: chatapp
description: A feature-rich Flutter chat application.

# Prevent accidental publishing to pub.dev
publish_to: "none"

# Application version and build number
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0" # Updated for latest Dart support

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.6 # Updated version
  flutter_svg: ^2.0.10+1  # Updated for better SVG support

  # Utilities & Storage
  shared_preferences: ^2.2.2 # Updated version
  path_provider: ^2.1.2 # Updated for latest compatibility
  path: ^1.8.3 # Specify version explicitly

  # Media Handling
  camera: ^0.10.5+4 # Updated camera package
  video_player: ^2.8.2 # Updated version

  # Real-time Communication
  socket_io_client: ^2.0.3 # Updated WebSocket support

  # Emoji Support
  emoji_picker_flutter: ^1.6.3 # Latest maintained emoji picker
  flutter_plugin_android_lifecycle: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/

  # Fonts
  fonts:
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-Bold.ttf
        - asset: fonts/OpenSans-Regular.ttf
        - asset: fonts/OpenSans-SemiBold.ttf
        - asset: fonts/OpenSans-Italic.ttf
          style: italic

